/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 34f7b3c2d0da01e8097306872b123d45)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env {
		ASSETS: Fetcher;
		CREATOR_NOTIFY_API_KEY: string;
		DB: D1Database;
		RESEND_API_KEY: string;
		VAPID_PRIVATE_KEY: string;
		VAPID_PUBLIC_KEY: string;
		VAPID_SUBJECT: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				"CREATOR_NOTIFY_API_KEY" | "RESEND_API_KEY" | "VAPID_PRIVATE_KEY" | "VAPID_PUBLIC_KEY" | "VAPID_SUBJECT"
			>
		> {}
}
