id: indivisiblelakemartindadeville
name: Indivisible Lake Martin Dadeville and Surrounding Area
hosts:
  - indivisiblelakemartindadeville.localhost
  - indivisiblelakemartindadeville.gloopglop.com
  - www.indivisiblelakemartindadeville.gloopglop.com
  - indivisiblelakemartindadeville.gloop.gg
  - www.indivisiblelakemartindadeville.gloop.gg
kind: platform
theme:
  preset: gloopglop
  mode: light
  overrides:
routing:
  default_page: index
  gloop_gg_short_slug: indlmd
permissions:
  view: public
  propose: members
  edit: restricted
  edit_mode: proposal_required
