id: thepaperjelly
name: The Paper Jelly
hosts:
  - thepaperjelly.localhost
  - thepaperjelly.gloopglop.com
  - www.thepaperjelly.gloopglop.com
  - thepaperjelly.gloop.gg
  - www.thepaperjelly.gloop.gg

kind: platform

theme:
  preset: gloopglop
  mode: light
  overrides:
    base-200: "#5989db"


routing:
  default_page: index
  gloop_gg_short_slug: tpj

permissions:
  view: public
  propose: members
  edit: restricted
  edit_mode: proposal_required