id: indivisibleweststclairmoody
name: Indivisible West St. Clair County (Moody)
hosts:
  - indivisibleweststclairmoody.localhost
  - indivisibleweststclairmoody.gloopglop.com
  - www.indivisibleweststclairmoody.gloopglop.com
  - indivisibleweststclairmoody.gloop.gg
  - www.indivisibleweststclairmoody.gloop.gg
kind: platform
theme:
  preset: gloopglop
  mode: light
  overrides:
routing:
  default_page: index
  gloop_gg_short_slug: indwsc
permissions:
  view: public
  propose: members
  edit: restricted
  edit_mode: proposal_required
