id: alabamafella
name: Alabamafella
hosts:
  - alabamafella.localhost
  - 127.0.0.1
  - alabamafella.gloopglop.com
  - www.alabamafella.gloopglop.com

kind: platform

theme:
  preset: gloopglop
  mode: light
  overrides:

navigation:
  header:
    - label: Home
      href: /
    - label: Tuscaloosa mutual aid
      href: /tuscaloosamutualaid

routing:
  default_page: index

permissions:
  view: public
  propose: members
  edit: restricted
  edit_mode: proposal_required