id: alabamafella
name: Alabamafella
hosts:
  - alabamafella.localhost
  - alabamafella.gloopglop.com
  - www.alabamafella.gloopglop.com
  - alabamafella.gloop.gg
  - www.alabamafella.gloop.gg

kind: platform

theme:
  preset: gloopglop
  mode: light
  overrides:



routing:
  default_page: index
  gloop_gg_short_slug: taf

permissions:
  view: public
  propose: members
  edit: restricted
  edit_mode: proposal_required