id: indivisiblephenixcity
name: Phenix City Indivisible
hosts:
  - indivisiblephenixcity.localhost
  - 127.0.0.1
  - indivisiblephenixcity.gloopglop.com
  - www.indivisiblephenixcity.gloopglop.com
  - indivisiblephenixcity.gloop.gg
  - www.indivisiblephenixcity.gloop.gg
kind: platform
theme:
  preset: gloopglop
  mode: light
  overrides:
routing:
  default_page: index
  gloop_gg_short_slug: indphe
permissions:
  view: public
  propose: members
  edit: restricted
  edit_mode: proposal_required
