id: gloopglop
name: GloopGlop
hosts:
  - localhost
  - 127.0.0.1
  - gloopglop.com
  - www.gloopglop.com
  - gloop.gg
  - www.gloop.gg
  - notifications-wikiglop.thecoopgal.workers.dev

kind: platform

theme:
  preset: gloopglop
  mode: dark
  overrides:
    
routing:
  default_page: index

permissions:
  view: public
  propose: members
  edit: restricted
  edit_mode: proposal_required