id: gloopglop
name: GloopGlop
hosts:
  - localhost
  - 127.0.0.1
  - me.localhost
  - gloopglop.com
  - www.gloopglop.com
  - me.gloopglop.com
  - gloop.gg
  - www.gloop.gg
  - notifications-wikiglop.thecoopgal.workers.dev

kind: platform

theme:
  preset: gloopglop
  mode: dark
  overrides:

short_links:
  - label: Home
    open_in: same_tab
    href: /

short_link_groups:
  - heading: Tools
    links:
      - label: Search
        open_in: same_tab
        href: /search
      - label: Watch
        open_in: same_tab
        href: /watch
      - label: Links
        open_in: same_tab
        href: /links
      - label: My pages
        open_in: same_tab
        href: /pages
      - label: Data
        open_in: same_tab
        href: /data
  - heading: About Us
    links:
      - label: Creators
        open_in: same_tab
        href: /creators
      - label: ByLaws
        open_in: same_tab
        href: /bylaws
      - label: Seven Principles
        open_in: same_tab
        href: /sevenprinciples
      - label: Consent
        open_in: same_tab
        href: /consent

routing:
  default_page: index

permissions:
  view: public
  propose: members
  edit: restricted
  edit_mode: proposal_required
